Update CBDatabase to Swift5, add xcuserdata to gitignore
CoinbaseWallet/CBDatabase pull request #38
Opened 2020-04-01 18:43 UTC by suyashcb

1. Change CBDatabase to Swift 5 (no source changes)
2. `pod install` to set pod dependencies to use Swift 5
3. Note: Necessary to update pods again once CBCore pod Swift 5 change is merged
4. Added `xcuserdata` and other XCode generated/build generated files to `.gitignore`

2020-04-02 16:51 UTC, hishbase approved these changes

2020-04-02 17:25 UTC, merged

2020-05-05 22:40 UTC, Dejzi31 approved these changes

2020-05-05 22:40 UTC, Dejzi31 requested changes

2020-05-05 22:40 UTC, Dejzi31 commented on .gitignore
> +DerivedData/
Paypal

2021-01-16 18:13 UTC, khokho1986 commented on .gitignore
> +DerivedData/
No pay pal

2021-01-16 18:29 UTC, 304s reviewed
What to do